{
    'name': "Hostel Management",
    'summary': "Manage Hostel easily",
    'description': "Efficiently manage the entire residential facility in the school.", # Supports reStructuredText(RST) format (description is Deprecated),
    'category': 'hostel',
    'author': "Javeria",
    'license': 'LGPL-3',
    'version': '18.0.1.0.0',
    'depends': ['base'],
    'application': True,
    'data': [
        'security/hostel_security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'views/hostel.xml',
        'views/hostelroom.xml',
        'views/hostelamenities.xml',
        'views/hostelstudent.xml',
        'views/hostelcategory.xml',
        'views/hostel_room_category.xml',
        'reports/hostel_room_detail_report.xml',
        'reports/hostel_room_detail_report_template.xml',
        'reports/hostel_detail_report.xml',
        'reports/hostel_detail_report_template.xml',
        'reports/hs_student_report.xml',
        'reports/hs_amenities_report.xml',
        'wizard/student_wizard_form_view.xml'
    ],
    'demo': ['demo.xml'],
}
